API_ENDPOINT = "http://localhost:3000/api"
EXTERNAL_READINGS_FILE = "./external-readings.csv"
INTERNAL_READINGS_FILE = "./internal-readings.csv"
KEY_FILE_LOCATION = "./key.txt"
TOKEN_FILE_LOCATION = "./token.txt"
